### ISSUE TITLE
latest version on pypi restricts protobuf to 3.x

### ISSUE THREAD

**Issue by koubaa** [ansys/ansys-api-mechanical#1]

**Comment by RobPasMue** [comment]
API packages should be using ``~3.19`` - this is required for all PyAnsys packages to work together.

See https://github.com/ansys/ansys-api-mechanical/blob/main/setup.py#L53

The protobuf bump on the API packages has to be done coordinated with the rest of the PyAnsys teams. We can bring it up in the dev meeting.

**Comment by klmcadams** [comment]
In the dev meeting they said if you have an explicit dependency on protobuf in your Python library, to please extend the upper limit of accepted version to include 4.x (https://github.com/ansys/ansys-api-mapdl/pull/11/files).

**Comment by RobPasMue** [comment]
> In the dev meeting they said if you have an explicit dependency on protobuf in your Python library, to please extend the upper limit of accepted version to include 4.x (https://github.com/ansys/ansys-api-mapdl/pull/11/files).

Yes, my previous comment was prior to that decision. =)

**Comment by koubaa** [comment]
Reopened until ansys-api-mechanical is released to PyPI

**Comment by klmcadams** [comment]
ansys-api-mechanical 0.1.1 has been released
